# Generated by Django 5.0.4 on 2024-04-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_settings_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutYourself',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название ваших положительных качеств')),
                ('subtitle', models.TextField(verbose_name='Описание ваших положительных качеств')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicPositions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=100, verbose_name='Профессия')),
                ('place', models.CharField(max_length=255, verbose_name='Учебное заведение')),
                ('data', models.DateField(verbose_name='Дата')),
            ],
        ),
        migrations.CreateModel(
            name='EducationTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('univercity', models.CharField(max_length=255, verbose_name='Название университета')),
                ('location', models.CharField(max_length=255, verbose_name='Адрес')),
                ('year', models.DateField(verbose_name='Год обучения')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logo_image/', verbose_name='Логотип')),
                ('title', models.CharField(max_length=255, verbose_name='Название тайтла')),
                ('data', models.CharField(max_length=255, verbose_name='Годы работы')),
                ('description', models.TextField(verbose_name='Описание опыта работы')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='settings_image/', verbose_name='Фото')),
                ('bio', models.CharField(max_length=255, verbose_name='ФИО')),
                ('review', models.TextField(verbose_name='О себе')),
            ],
        ),
        migrations.CreateModel(
            name='Rewards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Награды')),
                ('year', models.DateField(verbose_name='Год получения наград')),
            ],
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logo_image/', verbose_name='Логотип')),
                ('title', models.CharField(max_length=255, verbose_name='Название тайтла')),
                ('image_of_college', models.ImageField(upload_to='job_image/', verbose_name='Фото колледжа')),
                ('name_of_job', models.CharField(max_length=255, verbose_name='Название колледжа')),
                ('publication', models.DateField(verbose_name='Дата публикации')),
                ('description_of_college', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.RemoveField(
            model_name='settings',
            name='logo',
        ),
    ]
