# Generated by Django 5.0.4 on 2024-04-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_aboutyourself_academicpositions_educationtraining_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Settings',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='subreview',
            field=models.CharField(default=1, max_length=255, verbose_name='Комментарий'),
            preserve_default=False,
        ),
    ]
