# Generated by Django 5.0.4 on 2024-04-26 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_academicpositions_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicpositions',
            options={'verbose_name': '2)Академическая должность', 'verbose_name_plural': '2)Академическии должности'},
        ),
        migrations.AlterModelOptions(
            name='educationtraining',
            options={'verbose_name': '3)Образование/Обучение', 'verbose_name_plural': '3)Образовании/Обучении'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'verbose_name': '6)Опыт работы', 'verbose_name_plural': '6)Опыты работы'},
        ),
        migrations.AlterModelOptions(
            name='rewards',
            options={'verbose_name': '4)Награда', 'verbose_name_plural': '4)Награды'},
        ),
        migrations.AlterModelOptions(
            name='works',
            options={'verbose_name': '5)Прошлое место работы', 'verbose_name_plural': '5)Прошлые места работы'},
        ),
    ]
