# Generated by Django 5.0.4 on 2024-04-26 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_academicpositions_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicpositions',
            name='title',
        ),
    ]
