# Generated by Django 5.0.4 on 2024-04-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_academicpositions_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minetitle', models.CharField(max_length=255, verbose_name='Главный тайтл')),
                ('description', models.TextField(verbose_name='Описание')),
                ('title', models.CharField(max_length=255, verbose_name='Тайтл')),
                ('subdescription', models.TextField(verbose_name='Подописание')),
            ],
            options={
                'verbose_name': '8)Журналл',
                'verbose_name_plural': '8)Журналы ',
            },
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minetitle', models.CharField(max_length=255, verbose_name='Название исследования')),
                ('description', models.TextField(verbose_name='Описание')),
                ('subdescription', models.TextField(verbose_name='Подoписание')),
            ],
        ),
        migrations.AlterModelOptions(
            name='aboutyourself',
            options={'verbose_name': '7)Качество', 'verbose_name_plural': '7)Качества '},
        ),
        migrations.AlterField(
            model_name='aboutyourself',
            name='subtitle',
            field=models.TextField(verbose_name='Расскажите более подробно'),
        ),
    ]
