# Generated by Django 5.0.4 on 2024-04-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_journal_research_alter_aboutyourself_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_interests', models.CharField(max_length=255, verbose_name='Ваши интересы')),
            ],
            options={
                'verbose_name': '10)Интерес',
                'verbose_name_plural': '10)Интересы',
            },
        ),
        migrations.CreateModel(
            name='LatestBlogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название последних постов')),
                ('description', models.TextField(verbose_name='Описание')),
                ('date', models.DateField(verbose_name='Дата выпуска')),
                ('image', models.ImageField(upload_to='image/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': '11)Последний блог',
                'verbose_name_plural': '11)Последние блоги',
            },
        ),
        migrations.AlterModelOptions(
            name='journal',
            options={'verbose_name': '8)Журнал', 'verbose_name_plural': '8)Журналы'},
        ),
        migrations.AlterModelOptions(
            name='research',
            options={'verbose_name': '9)Иследование', 'verbose_name_plural': '9)Иследования'},
        ),
        migrations.AlterField(
            model_name='rewards',
            name='title',
            field=models.TextField(verbose_name='Наградa'),
        ),
        migrations.AlterField(
            model_name='rewards',
            name='year',
            field=models.DateField(verbose_name='Год получения награды'),
        ),
    ]
