# Generated by Django 5.0.4 on 2024-04-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_interests_latestblogs_alter_journal_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='settings_logo/', verbose_name='Логотип')),
                ('fullname', models.CharField(max_length=100, verbose_name='ФИО')),
                ('subdescription', models.TextField(verbose_name='Миниописание')),
                ('adout', models.CharField(max_length=100, verbose_name='О тебе')),
            ],
        ),
    ]
