# Generated by Django 5.0.4 on 2024-04-26 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='adout',
        ),
    ]
