# Generated by Django 5.0.4 on 2024-04-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_settings_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_office', models.TextField(verbose_name='Название офиса')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефон')),
            ],
        ),
    ]
