# Generated by Django 5.0.4 on 2024-04-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='email',
            field=models.EmailField(default=1, max_length=254, verbose_name='Почта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='twitter',
            field=models.URLField(default=1, verbose_name='Твиттер'),
            preserve_default=False,
        ),
    ]
