# Generated by Django 5.0.4 on 2024-04-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_contacts_email_contacts_twitter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='twitter',
        ),
        migrations.AddField(
            model_name='contacts',
            name='instagram',
            field=models.URLField(default=1, verbose_name='Instagram'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='whapsapp',
            field=models.URLField(default=1, verbose_name='Whatsapp'),
            preserve_default=False,
        ),
    ]
