# Generated by Django 5.0.4 on 2024-04-26 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_rename_whapsapp_contacts_whatsapp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': '12)Контакт', 'verbose_name_plural': '12)Контакты'},
        ),
    ]
