# Generated by Django 5.0.4 on 2024-04-27 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_remove_educationtraining_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewards',
            name='subtitle',
            field=models.TextField(default=1, verbose_name='Описание прогресса'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rewards',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Прогресс'),
        ),
        migrations.AlterField(
            model_name='rewards',
            name='year',
            field=models.DateField(verbose_name='Дата'),
        ),
    ]
