# Generated by Django 5.0.4 on 2024-04-27 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_rewards_subtitle_alter_rewards_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rewards',
            options={'verbose_name': '4)Прогресс', 'verbose_name_plural': '4)Прогрессы'},
        ),
    ]
