# Generated by Django 5.0.4 on 2024-04-27 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_rewards_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='works',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='works',
            name='title',
        ),
    ]
