# Generated by Django 5.0.4 on 2024-04-27 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_remove_works_logo_remove_works_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutyourself',
            options={'verbose_name': 'Качество', 'verbose_name_plural': 'Качества '},
        ),
        migrations.AlterModelOptions(
            name='academicpositions',
            options={'verbose_name': 'Академическая должность', 'verbose_name_plural': 'Академическии должности'},
        ),
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AlterModelOptions(
            name='educationtraining',
            options={'verbose_name': 'Образование/Обучение', 'verbose_name_plural': 'Образовании/Обучении'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'verbose_name': 'Опыт работы', 'verbose_name_plural': 'Опыты работы'},
        ),
        migrations.AlterModelOptions(
            name='interests',
            options={'verbose_name': 'Интерес', 'verbose_name_plural': 'Интересы'},
        ),
        migrations.AlterModelOptions(
            name='journal',
            options={'verbose_name': 'Журнал', 'verbose_name_plural': 'Журналы'},
        ),
        migrations.AlterModelOptions(
            name='latestblogs',
            options={'verbose_name': 'Последний блог', 'verbose_name_plural': 'Последние блоги'},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name': 'Портфолио', 'verbose_name_plural': 'Портфолии'},
        ),
        migrations.AlterModelOptions(
            name='research',
            options={'verbose_name': 'Иследование', 'verbose_name_plural': 'Иследования'},
        ),
        migrations.AlterModelOptions(
            name='rewards',
            options={'verbose_name': 'Прогресс', 'verbose_name_plural': 'Прогрессы'},
        ),
        migrations.AlterModelOptions(
            name='works',
            options={'verbose_name': 'Прошлое место работы', 'verbose_name_plural': 'Прошлые места работы'},
        ),
    ]
