# Generated by Django 5.0.4 on 2024-04-27 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_alter_aboutyourself_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='logo',
        ),
    ]
