# Generated by Django 5.0.4 on 2024-04-27 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_remove_experience_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='title',
        ),
    ]
