# Generated by Django 5.0.4 on 2024-04-27 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_remove_experience_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Journal',
            new_name='Plans',
        ),
        migrations.AlterModelOptions(
            name='plans',
            options={'verbose_name': 'План', 'verbose_name_plural': 'Планы'},
        ),
    ]
