# Generated by Django 5.0.4 on 2024-04-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_rename_journal_plans_alter_plans_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestblogs',
            name='autor',
            field=models.CharField(default=1, max_length=255, verbose_name='Автор'),
            preserve_default=False,
        ),
    ]
